---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quant-overledger-network-gateway.fullname" . }}-envmap
  labels:
    app: {{ include "quant-overledger-network-gateway.name" . }}
    chart: {{ include "quant-overledger-network-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $key,$value := .Values.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
